# version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - stock-network
    ports:
      - "80:80" # 단일 포트 사용
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - jupyter
      - comfy
    restart: always
  db:
    image: postgres-img
    container_name: db
    hostname: db
    build: ./postgres
    networks:
      - stock-network
    env_file:
      - ./postgres/.env
    user: "1001:1001"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: always

  collector:
    image: data-collector-img
    container_name: collector
    hostname: collector
    build: ./data-collector
    networks:
      - stock-network
    volumes:
      - ./data/raw:/data
      - ./data-collector:/app
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  quant:
    image: quant-analyzer-img
    container_name: quant
    hostname: quant
    build: ./quant-analyzer
    networks:
      - stock-network
    volumes:
      - ./data/processed:/data
      - ./quant-analyzer:/app
    depends_on:
      collector:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  ai:
    image: ai-predictor-img
    container_name: ai
    hostname: ai
    build:
      context: .
      dockerfile: ai-predictor/Dockerfile
    networks:
      - stock-network
    volumes:
      - ./data/models:/data
      - ./ai-predictor:/app
    depends_on:
      quant:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
        limits:
          memory: 4G
          cpus: "1"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_HOME=/usr/local/cuda
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/nvidia-cuda-toolkit/libdevice
    runtime: nvidia

  web:
    image: web-interface-img
    container_name: web
    hostname: web
    build: ./web-interface
    networks:
      - stock-network
    # ports:
    #   - "5000:5000"
    volumes:
      - ./web-interface:/app
    depends_on:
      db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
    restart: always
  comfy:
    image: comfy-ui-img
    container_name: comfy
    hostname: comfy
    user: "1000:1000"
    build: ./comfy-ui
    networks:
      - stock-network
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COMFYUI_LOAD_CUSTOM_NODES=1
    # ports:
    #   - 7860:7860
    deploy:
      resources:
        limits:
          memory: 20G
          cpus: "4"
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    runtime: nvidia
    volumes:
      - ./comfy-ui:/home/user/app
    restart: always
  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter
    networks:
      - stock-network
    # ports:
    #   - "8888:8888"
    volumes:
      - ../design/models:/home/jovyan/models
      - ../design/uploads:/home/jovyan/uploads
      - ../design/notebooks:/home/jovyan/notebooks
      - ./web-interface:/home/jovyan/web-interface
    environment:
      - JUPYTER_ENABLE_LAB=yes
    # command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_remote_access=True --NotebookApp.ip='0.0.0.0'"
    command: [ "start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''", "--NotebookApp.ip='0.0.0.0'", "--NotebookApp.base_url=/jupyter" ]
    restart: always

networks:
  stock-network:
    driver: bridge
